#print("what is the raidus of this ciricle")
#raidus=int(input())
#area =int(input(3.14 * raidus * raidus))
#print(area)

print("what is the length of the tringle")
print("what is the width of the rectangle")
width = int(input())
length =int(input())
peremeter = ((2*(length+width)))
print(peremeter)

#print("enter your first number")
num1 = int(input("enter your first num"))
#print("enter your second number")
num2 = int(input("enter your seond num"))
product = (num1*num2)
sum = (num1 + num2)
avg = ((num1 + num2)/2)
print(sum, avg, product)

print("how many talents are needed")
talents = int(input(pounds*20))
print("how many pounds are nedded ")
pounds =  int(input(lots*32 ))
print("how many lots are needed")
lots = int(input(13.3))
print(talents,pounds,lots)
