#print("what is the raidus of this ciricle")
#raidus=int(input())
#area =int(input(3.14 * raidus * raidus))
#print(area)

print("what is the length of the tringle")
print("what is the width of the rectangle")
width = int(input())
length =int(input())
peremeter = (2*width + 2*length)
print(peremeter)